# Name of workflow
name: PHP CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    steps:
      # Check-out repository under GitHub workspace
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
        # Step's name
      - name: Setup PHP
        # Action gives to setup the PHP environment to test application
        # https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          # Specify the PHP version
          php-version: '7.4'
      - name: Install
        # Install project
        run: make install
      - name: Run linter
        # Run Linter
        run: make lint
      - name: Test
        #Test project
        run: make test

      - name: coverage
          #Test coverage project
            - run: npm install -g yarn
            - run: yarn install
            - run: yarn build
            - uses: paambaati/codeclimate-action@v2.2.4
              env:
                CC_TEST_REPORTER_ID: 945dfb58a832d233a3caeb84e3e6d3be212e8c7abcb48117fce63b9adcb43647
              with:
                coverageCommand: yarn coverage


